name: GenTx
on:
  pull_request:
    branches:
      - main
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18
      - name: Install build-essential
        run:  sudo apt install build-essential jq -y
      - name: Checkout code
        uses: actions/checkout@v2
      - name: validate-gentx
        run: |
          bash -x ./scripts/verify_gentx.sh